### PR TITLE
progress, tesseract config, roi, debug image

### PR DESCRIPTION
**Pull request by kftsehk**
A few features to the API that I find useful

- `tesseract_config: str`: extra config that will be passed directly to tesseract, changing some of these configs may increase accuracy
- `roi: [[float, float], [float, float]]`: replaces `use_fullframe`, allow specifying region of interest in terms of % of video height and width, exact syntax is `[[x_start, x_end], [y_start, y_end]]`, default is `[[0,1],[0,1]]` which is equal to `use_fullframe=True`
- `num_jobs: int`: `num_cpus` to `p_tqdm`, p_tqdm shows a progress bar and estimated completion time, which can be useful for longer video.
- `debug: bool`: If true, writes each ROI frame to working directory, useful for adjusting ROI.

Example usage:

```python
save_subtitles_to_file(
        video_path='video.mp4',
        file_path='video.srt',
        lang='chi_tra+chi_sim', tesseract_config="--psm 6 --oem 3 --dpi 300",
        time_start='0:00', time_end='',
        conf_threshold=60, sim_threshold=90,
        roi=[[0.2,0.8],[0.90, 0.98]],
        debug=True,
        num_jobs=4,
    )
```

Some findings not patched:
- There are 3 sets of datafile, different data may perform better or less [official github](https://tesseract-ocr.github.io/tessdoc/Data-Files.html)
- Filling all cores with tesseract may not be fastest

### CODE REVIEW

**Comment by VladiStep** [comment]
I tried to use your modified version, but at some point it stops with "The system cannot write to the specified device" error...

**Comment by VladiStep** [comment]
@kftsehk, I tried to use your modified version, but at some point it stops with "The system cannot write to the specified device" error...

**Comment by kftsehk** [comment]
hi, the program will write the srt file, and the updated version with debug enabled will also write each frame’s region of interest.

Please confirm you do not have an issue with disk capacity, and post a stack trace.

**Comment by VladiStep** [comment]
@kftsehk, how do I get a stack trace? It just prints that message, no details.

**Pull request closed without merging**
